import importlib.util
import json
from pathlib import Path

import pytest


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "audit/e9f/qp_b_c2_c3_r8_c2_convergence_method_audit.py"
DIAGNOSIS = ROOT / "audit/e9f/qp_b_c2_c3_r8_c2_convergence_diagnosis.json"
CONTRACT = ROOT / "audit/e9f/qp_b_c2_c3_r8_c2_prospective_validation_contract.json"


def load_script():
    spec = importlib.util.spec_from_file_location("_r8_c2_method_audit_test", SCRIPT)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def analysis():
    module = load_script()
    return module, module.analyze()


def test_exact_srd_and_classification_logic():
    module = load_script()
    assert module.srd(0.0, 0.0) == 0.0
    assert module.srd(1.0, -1.0) == 2.0
    assert module.relation(2.0, 1.0, contraction="C", expansion="E", equality="Q") == "C"
    assert module.relation(2.0, 3.0, contraction="C", expansion="E", equality="Q") == "E"
    assert module.relation(2.0, 2.0, contraction="C", expansion="E", equality="Q") == "Q"


def test_counts_and_first_method_audit_decision(analysis):
    _, result = analysis
    assert result["dataset"]["record_count"] == 210
    assert result["execution"] == {
        "native_invocations": 0,
        "provider_requests": 0,
        "solver_executions": 0,
        "mpb_execution": False,
    }
    assert result["counts"] == {
        "sample_count": 8,
        "srd_normalization_reversal_count": 4,
        "abs_stencil_difference_expands_count": 3,
        "both_stencil_resolution_contraction_count": 6,
        "nonmonotonic_resolution_sequence_count": 4,
    }
    assert result["method_audit_decision"] == (
        "STENCIL_SRD_MONOTONIC_CONTRACTION_NOT_JUSTIFIED_AS_GENERAL_SOLVER_CONVERGENCE_REQUIREMENT"
    )


def test_known_sample_diagnostics_and_role_counts(analysis):
    _, result = analysis
    samples = result["samples"]
    control_2 = samples["fr=0;grid_i=-34;grid_j=9;estimator=SOURCE_GRID"]
    diagnostic = samples["fr=0;grid_i=-6;grid_j=-1;estimator=SOURCE_GRID"]
    near_gamma = samples["fr=0;grid_i=-4;grid_j=0;estimator=SOURCE_GRID"]
    assert control_2["srd_normalization_reversal"] is True
    assert control_2["nonmonotonic_resolution_sequence"] is True
    assert diagnostic["abs_stencil_difference_classification"] == "ABS_STENCIL_DIFFERENCE_EXPANDS"
    assert near_gamma["resolution_increment_contraction_at_both_stencils"] is False
    assert result["counts_by_role"]["CALIBRATION_CONTROL"]["sample_count"] == 2
    assert result["counts_by_role"]["STENCIL_DIAGNOSTIC"]["sample_count"] == 1
    assert result["counts_by_role"]["POLICY_CHALLENGE"]["sample_count"] == 5


def test_public_artifacts_are_bounded_and_contract_is_nonexecuting(analysis):
    module, result = analysis
    diagnosis = module.diagnosis_artifact(result)
    contract = module.contract_artifact(result)
    assert diagnosis["current_c1_verdict_unchanged"] is True
    assert diagnosis["prior_c1_verdict"]["current_0p02_policy_calibration"] == "INCONCLUSIVE"
    assert contract["nonexecuting"] is True
    assert contract["holdout"]["sample_id"] == "fr=0;grid_i=-34;grid_j=16;estimator=SOURCE_GRID"
    serialized = json.dumps({"diagnosis": diagnosis, "contract": contract}, ensure_ascii=False)
    assert "h_fields" not in serialized
    assert "normalized_vectors" not in serialized
    assert "/home/" not in serialized


def test_tracked_artifacts_equal_bounded_projections(analysis):
    module, result = analysis
    if not DIAGNOSIS.exists() or not CONTRACT.exists():
        pytest.skip("artifacts are generated by the zero-argument entrypoint")
    assert json.loads(DIAGNOSIS.read_text(encoding="utf-8")) == module.diagnosis_artifact(result)
    assert json.loads(CONTRACT.read_text(encoding="utf-8")) == module.contract_artifact(result)


def test_source_has_no_solver_or_provider_execution_path():
    source = SCRIPT.read_text(encoding="utf-8")
    assert "build_r8_provider_factory(" not in source
    assert "_build_live_provider(" not in source
    assert "run-native" not in source
